version: '2'
services:

  postgres:
    image: ggcsr-pg11alpine
    ports:
    - "6432:5432"
 
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=P4ssw0rD
    ports:
    - "1443:1443"

