version: '2'
services:

  postgres:
    image: ggcsr-pg11alpine
    ports:
    - "6432:5432"
 
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=P4ssw0rD
    ports:
    - "1443:1443"

    #networks:
    #  eidas_net:
    #    ipv4_address: 172.16.238.14

#networks:
#  eidas_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#      - subnet: 172.16.238.0/24
#        gateway: 172.16.238.1   
