version: '3.6'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=P4ssw0rD
    ports:
    - "1443:1443"
  postgres:
    build: 
      context: ./pg11alpine-tds_fdw
      dockerfile: ./Dockerfile  
      args: 
        PGDATA: /var/lib/pgsql/data
        PGADMINPASS: postgres
        PGPGPASS: postgres
        PGDBNAME: workspace
        MSSQL_SERVER: mssql
        MSSQL_DB: master
        MSSQL_USER: sa
        MSSQL_PASS: P4ssw0rD
        MSSQL_SCHEMA: dbo
    image: cbusoi/pg11alpine-tds_fdw
    environment:
      PGDATA: /var/lib/pgsql/data
      IMPORT_SERVER: import_server
      IMPORT_SCHEMA: import_schema
      MSSQL_SCHEMA: dbo
    ports:
#    - "5432:5432"
    - "5432"
    depends_on:
    - "mssql"
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/pgsql/data
      volume:
        nocopy: true
    command:
    - "su postgres -c postgres -i -c config_file=/var/lib/pgsql/data/postgresql.conf"
    - "su postgres -c echo IMPORT FOREIGN SCHEMA dbo FROM SERVER import_server INTO import_schema OPTIONS (import_default 'true') | psql -U postgres -d workspace"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgres
    ports:
      - "4000:4000"
volumes:
  db-data:
