apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mssql
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mssql
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mssql
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: Y
        - name: SA_PASSWORD
          value: P4ssw0rD
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        imagePullPolicy: ""
        name: mssql
        ports:
        - containerPort: 1443
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
