apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - args:
        - su postgres -c echo IMPORT FOREIGN SCHEMA dbo FROM SERVER import_server
          INTO import_schema OPTIONS (import_default 'true') | psql -U postgres -d
          workspace
        env:
        - name: IMPORT_SCHEMA
          value: import_schema
        - name: IMPORT_SERVER
          value: import_server
        - name: MSSQL_SCHEMA
          value: dbo
        image: cbusoi/pg11alpine-tds_fdw
        imagePullPolicy: ""
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/data/pg
          name: postgres-claim0
        - mountPath: /var/lib/pgsql/data
          name: db-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: postgres-claim0
        persistentVolumeClaim:
          claimName: postgres-claim0
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
status: {}
